apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.inventory.secret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  # The b64enc function converts the plain text string to base64
  DATABASE_URL: {{ .Values.inventory.secret.DATABASE_URL | b64enc | quote }}
