apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.notifactions.secret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  SMTP_HOST: {{ .Values.notifactions.secret.SMTP_HOST | b64enc | quote }}
  SMTP_USER: {{ .Values.notifactions.secret.SMTP_USER | b64enc | quote }}
  SMTP_PASSWORD: {{ .Values.notifactions.secret.SMTP_PASSWORD | b64enc | quote }}

